version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: media
      MYSQL_USER: developer
      MYSQL_PASSWORD: password

  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/workdir/app
    working_dir: /workdir/app 
    command: fresh 
    restart: always
    depends_on:
      - db
    ports:
      - "1323:1323"

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"

  redisCommander:
    image: tenstartups/redis-commander
    restart: always
    command: --redis-host redis
    depends_on:
      - redis
    links:
      - redis:redis
    ports:
      - '8081:8081'

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./swagger-editor/doc/rest-api.yml:/usr/share/nginx/html/rest-api.yml
    environment:
      API_URL: rest-api.yml
    ports:
      - '8080:8080'

  swagger-editor:
    build: ./swagger-editor
    restart: always
    volumes:
      - ./swagger-editor/doc:/doc
    ports:
      - "8888:8765"

#  nginx:
#    build: ./nginx
#    command: sleep infinity 
#    ports:
#      - '80:80'

  nginx:
    image: openresty/openresty:alpine
    restart: always
    volumes:
      - ./nginx/conf:/usr/local/openresty/nginx/conf
      - ./nginx/sample.lua:/usr/local/luafiles/sample.lua
    depends_on:
      - redis
    links:
      - redis:redis
    ports:
      - '80:80'

volumes:
  db_data:
