version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: media
       MYSQL_USER: developer
       MYSQL_PASSWORD: password

   #wordpress:
   #  depends_on:
   #    - db
   #  image: wordpress:latest
   #  ports:
   #    - "8000:80"
   #  restart: always
   #  environment:
   #    WORDPRESS_DB_HOST: db:3306
   #    WORDPRESS_DB_USER: wordpress
   #    WORDPRESS_DB_PASSWORD: wordpress

   app:
     build: ./app
     volumes:
       - ./app:/workdir/app
     working_dir: /workdir/app 
     command: go run main.go
     depends_on:
       - db
     ports:
       - "1323:1323"
       - '50022:22'
volumes:
    db_data:
