version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: media
      MYSQL_USER: developer
      MYSQL_PASSWORD: password

  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/workdir/app
    working_dir: /workdir/app 
    command: fresh 
    restart: always
    depends_on:
      - db
      - session-redis
      - domain-redis
    links:
      - session-redis:session-redis
      - domain-redis:domain-redis
    ports:
      - "1323:1323"

  session-redis:
    image: "redis:alpine"
    restart: always
    #ports:
    #  - "6379:6379"
    expose:
      - "6379"

  domain-redis:
    #image: "redis:alpine"
    image: "redis:alpine"
    restart: always
    #command: sh -c "redis-server --daemonize yes && redis-cli -h domain-redis"
    #command: redis-server --appendonly yes
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"

  redis-fixture:
    image: "goodsmileduck/redis-cli:latest"
    command: redis-cli -h domain-redis set bozublog.dev 1
    depends_on:
      - session-redis
      - domain-redis
    links:
      - session-redis:session-redis
      - domain-redis:domain-redis

  redisCommander:
    image: tenstartups/redis-commander
    restart: always
    command: --redis-host domain-redis
    depends_on:
      - domain-redis
    links:
      - domain-redis:domain-redis
    ports:
      - '8081:8081'

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./swagger-editor/doc/rest-api.yml:/usr/share/nginx/html/rest-api.yml
    environment:
      API_URL: rest-api.yml
    ports:
      - '8080:8080'

  swagger-editor:
    build: ./swagger-editor
    restart: always
    volumes:
      - ./swagger-editor/doc:/doc
    ports:
      - "8888:8765"

#  nginx:
#    build: ./nginx
#    command: sleep infinity 
#    ports:
#      - '80:80'

  nginx:
    image: openresty/openresty:alpine
    restart: always
    volumes:
      - ./nginx/conf:/usr/local/openresty/nginx/conf
    depends_on:
      - domain-redis
    links:
      - domain-redis:domain-redis
    ports:
      - '80:80'

volumes:
  db_data:
