swagger: "2.0"
info: 
  version: "1.0.0"
  title: "Blog API"
  description: "Blog API"
  termsOfService: "http://localhost:1323"
host: "localhost:1323"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/x-www-form-urlencoded"
produces: 
  - "application/json"
paths: 
  /{media_id}/articles: 
    get: 
      description: "記事一覧"
      operationId: "articles"
      produces: 
        - "application/json"
      parameters: 
        - 
          name: "media_id"
          in: "path"
          description: "メディアID"
          required: true
          type: "integer"
        - 
          name: "limit"
          in: "query"
          description: "取得件数"
          required: false
          type: "integer"

        - 
          name: "offset"
          in: "query"
          description: "開始位置"
          required: false
          type: "integer"
      responses: 
        "200":
          description: "通常取得"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/Pet"
        "401":
          description: "need authentication"
          schema: 
            type: "object"
            items: 
              $ref: "#/definitions/Pet"
        default: 
          description: "unexpected error"
          schema: 
            $ref: "#/definitions/ErrorModel"
  /{media_id}/article/{article_id}: 
    get: 
      description: "記事の取得"
      operationId: "article"
      produces: 
        - "application/json"
      parameters: 
        - 
          name: "media_id"
          in: "path"
          description: "メディアID"
          required: true
          type: "integer"
          format: "int64"
        - 
          name: "article_id"
          in: "path"
          description: "記事ID"
          required: true
          type: "integer"
          format: "int64"
      responses: 
        "200":
          description: "通常取得"
          schema: 
            $ref: "#/definitions/Article"
        "401":
          description: "need authentication"
          schema: 
            type: "object"
            items: 
              $ref: "#/definitions/Pet"
        default: 
          description: "unexpected error"
          schema: 
            $ref: "#/definitions/ErrorModel"
            
  /login:
    post:
      description: "ログイン"
      consumes: 
        - "application/x-www-form-urlencoded"
      parameters:
        - name: email 
          in: formData
          description: メールアドレス
          required: true
          type: "string"
        - name: password
          in: formData
          description: パスワード
          required: true
          type: "string"


      produces: 
        - "application/json"
      responses: 
        "200":
          description: "通常取得"
          schema: 
            $ref: "#/definitions/Login"
        "401":
          description: "need authentication"
          schema: 
            type: "object"
            items: 
              $ref: "#/definitions/Pet"
        default: 
          description: "unexpected error"
          schema: 
            $ref: "#/definitions/ErrorModel"

definitions: 
  Article: 
    type: "object"
    required: 
      - "msg"
      - "result"
    properties: 
      msg: 
        type: "string"
      result: 
        type: "object"
  Pet: 
    type: "object"
    required: 
      - "name"
    properties: 
      name: 
        type: "string"
      tag: 
        type: "string"
  Login: 
    type: "object"
    required: 
      - "msg"
      - "result"
    properties: 
      msg: 
        type: "string"
      result: 
        type: "boolean"

  ErrorModel: 
    type: "object"
    required: 
      - "msg"
      - "result"
    properties: 
      msg: 
        type: "string"
      result: 
        type: "object"

