FROM golang:1.8.0

RUN go get -u github.com/go-sql-driver/mysql \
      github.com/jmoiron/sqlx \
      github.com/labstack/echo \
      gopkg.in/gorp.v1 \
      bitbucket.org/liamstask/goose/cmd/goose \
