FROM golang:1.8.0

RUN go get -u github.com/go-sql-driver/mysql \
      github.com/jmoiron/sqlx \
      github.com/labstack/echo \
      gopkg.in/gorp.v1 \
      bitbucket.org/liamstask/goose/cmd/goose \
      gopkg.in/godo.v2/cmd/godo \
      github.com/pilu/fresh \
      github.com/gorilla/sessions \
      github.com/labstack/echo-contrib \
      github.com/ipfans/echo-session \
      github.com/dgrijalva/jwt-go \
      github.com/utahta/echo-sessions \
      github.com/boj/redistore


