FROM golang:1.8.0

RUN go get -u github.com/go-sql-driver/mysql 
RUN go get -u github.com/jmoiron/sqlx                  
RUN go get -u github.com/labstack/echo                 
RUN go get -u gopkg.in/gorp.v1                         
RUN go get -u bitbucket.org/liamstask/goose/cmd/goose  
RUN go get -u github.com/pilu/fresh                   
RUN go get -u github.com/gorilla/sessions              
RUN go get -u github.com/labstack/echo-contrib 
RUN go get -u github.com/ipfans/echo-session           
RUN go get -u github.com/dgrijalva/jwt-go              
RUN go get -u github.com/boj/redistore
